name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Build packages
        run: bun run build

      - name: Run tests
        run: DEV=true bun test # DEV necessary to run all tests

      - name: Run lint
        run: bun lint
